USE dbtestewk;

CREATE TABLE IF NOT EXISTS CLIENTES ( ID_Cliente Integer NOT NULL AUTO_INCREMENT
									, NM_Cliente VarChar(80) NOT NULL
                                    , NM_Cidade  VarChar(80) NOT NULL
                                    , NM_UF      Char(2) NOT NULL
                                    , primary key(ID_Cliente));
                                    
INSERT INTO CLIENTES (NM_Cliente, NM_Cidade, NM_UF) VALUES ('THALES RIBEIRO', 'ADAMANTINA', 'SP');
INSERT INTO CLIENTES (NM_Cliente, NM_Cidade, NM_UF) VALUES ('ALISSON', 'ADAMANTINA', 'SP');
INSERT INTO CLIENTES (NM_Cliente, NM_Cidade, NM_UF) VALUES ('EDERSON', 'TUPÃ', 'SP');
INSERT INTO CLIENTES (NM_Cliente, NM_Cidade, NM_UF) VALUES ('WEVERTON', 'MARINGA', 'PR');
INSERT INTO CLIENTES (NM_Cliente, NM_Cidade, NM_UF) VALUES ('DANIEL ALVES', 'BRASILIA', 'DF');
INSERT INTO CLIENTES (NM_Cliente, NM_Cidade, NM_UF) VALUES ('DANILO', 'BRASILIA', 'DF');
INSERT INTO CLIENTES (NM_Cliente, NM_Cidade, NM_UF) VALUES ('ALEX SANDRO', 'BRASILIA', 'DF');
INSERT INTO CLIENTES (NM_Cliente, NM_Cidade, NM_UF) VALUES ('ALEX TELLES', 'BRASILIA', 'DF');
INSERT INTO CLIENTES (NM_Cliente, NM_Cidade, NM_UF) VALUES ('BREMER', 'SAO PAULO', 'SP');
INSERT INTO CLIENTES (NM_Cliente, NM_Cidade, NM_UF) VALUES ('EDER MILITAO', 'SAO PAULO', 'SP');
INSERT INTO CLIENTES (NM_Cliente, NM_Cidade, NM_UF) VALUES ('MARQUINHOS', 'SAO PAULO', 'SP');
INSERT INTO CLIENTES (NM_Cliente, NM_Cidade, NM_UF) VALUES ('THIAGO SILVA', 'SAO PAULO', 'SP');
INSERT INTO CLIENTES (NM_Cliente, NM_Cidade, NM_UF) VALUES ('BRUNO GUIMARAES', 'SAO PAULO', 'SP');
INSERT INTO CLIENTES (NM_Cliente, NM_Cidade, NM_UF) VALUES ('CASEMIRO', 'SAO PAULO', 'SP');
INSERT INTO CLIENTES (NM_Cliente, NM_Cidade, NM_UF) VALUES ('EVERTON RIBEIRO', 'SAO PAULO', 'SP');
INSERT INTO CLIENTES (NM_Cliente, NM_Cidade, NM_UF) VALUES ('FABINHO', 'SAO PAULO', 'SP');
INSERT INTO CLIENTES (NM_Cliente, NM_Cidade, NM_UF) VALUES ('FRED', 'RIO DE JANEIRO', 'RJ');
INSERT INTO CLIENTES (NM_Cliente, NM_Cidade, NM_UF) VALUES ('LUCAS PAQUETA', 'RIO DE JANEIRO', 'RJ');
INSERT INTO CLIENTES (NM_Cliente, NM_Cidade, NM_UF) VALUES ('ANTONY', 'SAO PAULO', 'SP');
INSERT INTO CLIENTES (NM_Cliente, NM_Cidade, NM_UF) VALUES ('GABRIEL JESUS', 'SAO PAULO', 'SP');
INSERT INTO CLIENTES (NM_Cliente, NM_Cidade, NM_UF) VALUES ('GABRIEL MARTINELLI', 'SAO PAULO', 'SP');
INSERT INTO CLIENTES (NM_Cliente, NM_Cidade, NM_UF) VALUES ('NEYMAR', 'SAO PAULO', 'SP');
INSERT INTO CLIENTES (NM_Cliente, NM_Cidade, NM_UF) VALUES ('PEDRO', 'SAO PAULO', 'SP');
INSERT INTO CLIENTES (NM_Cliente, NM_Cidade, NM_UF) VALUES ('RAPHINHA', 'SAO PAULO', 'SP');
INSERT INTO CLIENTES (NM_Cliente, NM_Cidade, NM_UF) VALUES ('RICHARLISON', 'SAO PAULO', 'SP');
INSERT INTO CLIENTES (NM_Cliente, NM_Cidade, NM_UF) VALUES ('RODRYGO', 'SAO PAULO', 'SP');
INSERT INTO CLIENTES (NM_Cliente, NM_Cidade, NM_UF) VALUES ('VINICIUS JUNIOR', 'SAO PAULO', 'SP');